### ISSUE TITLE
[Bug] Crash upon opening a stream

### ISSUE THREAD

**Issue by OnionSin936** [Perflyst/Twire#75]
Version: 1.9.9
OS: 9.0 Pie

App crashes when opening streams after several usage.
It only happens when you are logged in to an twitch account.
Logging out / clearing app data will temporary fix it.

logs:

>  time: 1581005139893
msg: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: com.perflyst.twire.model.Emote$GetBestAvailableSize
stacktrace: java.lang.RuntimeException: Unable to invoke no-args constructor for interface com.perflyst.twire.model.Emote$GetBestAvailableSize. Registering an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.perflyst.twire.service.Settings.getRecentEmotes(Settings.java:180)
	at com.perflyst.twire.fragments.ChatFragment.loadRecentEmotes(ChatFragment.java:397)
	at com.perflyst.twire.fragments.ChatFragment.onCreateView(ChatFragment.java:182)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7165)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2972)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6672)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: com.perflyst.twire.model.Emote$GetBestAvailableSize
	at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117)
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
	... 40 more

**Comment by weinland** [comment]
Possible clone of #86 ?
Cheers,
Tristan
