### ISSUE TITLE
Sign in loop

### ISSUE THREAD

**Issue by Flam3z** [Perflyst/Twire#92]
Everytime i go through the login steps it loops me back to the Beginning and doesn't actually sign me in.

**Comment by ipha** [comment]
Same here. Throws this when I try to log in:
```05-30 14:15:39.042 10393 11144 V AddFollowsToDB: Entered AddFollowsToDB
05-30 14:15:39.045 10393 11144 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-30 14:15:39.045 10393 11144 E AndroidRuntime: Process: com.perflyst.twire, PID: 10393
05-30 14:15:39.045 10393 11144 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:353)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
05-30 14:15:39.045 10393 11144 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.ref.WeakReference cannot be cast to android.content.Context
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at com.perflyst.twire.tasks.AddFollowsToDB.doInBackground(AddFollowsToDB.java:36)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at com.perflyst.twire.tasks.AddFollowsToDB.doInBackground(AddFollowsToDB.java:24)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-30 14:15:39.045 10393 11144 E AndroidRuntime:        ... 3 more
05-30 14:15:39.051   429 10382 W ActivityManager: Process com.perflyst.twire has crashed too many times: killing!```

**Comment by samfun123** [comment]
@ipha Really appreciate the log! Hopefully this is fixed now. Let me know if you run into any issues.
